package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;
    private DbIterator child1, child2;
    private Tuple curT1 = null;
    private boolean isEqual;
    private HashEquiJoin hej;
    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        isEqual = p.getOperator().equals(Predicate.Op.EQUALS);
        if (isEqual)
            this.hej = new HashEquiJoin(p, child1, child2);
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        if (isEqual)
            hej.open();
        else {
            child1.open();
            child2.open();
        }
        super.open();
    }

    public void close() {
        // some code goes here
        super.close();
        if (isEqual)
            hej.close();
        else {
            child1.close();
            child2.close();
        }
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if (isEqual)
            return hej.fetchNext();
        if (curT1 == null && child1.hasNext())
            curT1 = child1.next();
        Tuple t2;
        while (curT1 != null){
            while (child2.hasNext()){
                t2 = child2.next();
                if (p.filter(curT1, t2)) {
                    Tuple ret = new Tuple(getTupleDesc());

                    for (int i = 0; i < child1.getTupleDesc().numFields(); ++i)
                        ret.setField(i, curT1.getField(i));

                    for (int i = 0; i < child2.getTupleDesc().numFields(); ++i)
                        ret.setField(i + child1.getTupleDesc().numFields(), t2.getField(i));

                    return ret;
                }
            }
            if (child1.hasNext()) {
                curT1 = child1.next();
                child2.rewind();
            }
            else break;
        }
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return new DbIterator[]{child1, child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        child1 = children[0];
        child2 = children[1];
        if (isEqual)
            hej.setChildren(children);

    }

}
